### ISSUE TITLE
OpenAPI Docs?

### ISSUE THREAD

**Issue by 0mars** [danizavtz/tokenAuth#1]
Do you have openAPI docs for this service ?

**Comment by danizavtz** [comment]
I do not write. But i can provide. This project just has 3 routes, I do not thought it was necessary. In my personal projects I use swagger.

**Comment by danizavtz** [comment]
Created a new branch called apidocs. 
https://github.com/danizavtz/tokenAuth/tree/apidocs

You can change to this branch, do a npm install and access the route:
/api-docs
In your current server.
If this fits your requirements, let me know. And I will close that issue.

**Comment by danizavtz** [comment]
As it didn't have any interaction since the branch published, I'm considering it is fixed, if you need more information, let me know.
